### ISSUE TITLE
Error in Common.agda?

### ISSUE THREAD

**Issue by watashiwa-toki** [UlfNorell/x86-agda#2]
Trying use:

module foo where
open import X86

causes an error:

C:\agdalib\x86-agda\src\X86\Common.agda:5,13-30
Failed to find source of module Structure.Smashed in any of the
following locations:
  C:\agdatest\Structure\Smashed.agda
  C:\agdatest\Structure\Smashed.lagda
  C:\agdalib\standard-library\src\Structure\Smashed.agda
  C:\agdalib\standard-library\src\Structure\Smashed.lagda
  C:\agdalib\agda-prelude\src\Structure\Smashed.agda
  C:\agdalib\agda-prelude\src\Structure\Smashed.lagda
  C:\agdalib\plfa\src\Structure\Smashed.agda
  C:\agdalib\plfa\src\Structure\Smashed.lagda
  C:\agdalib\x86-agda\src\Structure\Smashed.agda
  C:\agdalib\x86-agda\src\Structure\Smashed.lagda
  C:\sr\snapshots\d726c829\share\x86_64-windows-ghc-8.4.4\Agda-2.5.4.2\lib\prim\Structure\Smashed.agda
  C:\sr\snapshots\d726c829\share\x86_64-windows-ghc-8.4.4\Agda-2.5.4.2\lib\prim\Structure\Smashed.lagda
when scope checking the declaration
  open import Structure.Smashed

x86-agda library in AGDA_DIR directory and declared in "defaults" and "libraries" configs. What i doing wrong?

**Comment by gallais** [comment]
I've pushed an update to bring the project up to speed with 2.5.4.2 here:
https://github.com/gallais/x86-agda

I can open a PR if you're interested @UlfNorell.

**Comment by UlfNorell** [comment]
Sure thanks!

**Comment by UlfNorell** [comment]
Closed by #3.
